n=int(input())
print('left shift at 1',n<<1)
print('left shift at 2',n<<2)
print('left shift at 3',n<<3)
print('left shift at 4',n<<4)
print('left shift at 5',n<<5)
print('left shift at 6',n<<6)
print('left shift at 7',n<<7)
print('left shift at 8',n<<8)
print('left shift at 9',n<<9)